### ISSUE TITLE
Unpin Java dependency version

### ISSUE THREAD

**Issue by tnation14** [azavea/ansible-opentripplanner#29]
Currently, in `meta/main.yml`, we pin the Java installation version to `8u111*`. This version was recently removed from the WebUpd8 PPA, so installing this role errors out:

```
otp: PLAY [otp] *********************************************************************
    otp:
    otp: TASK [setup] *******************************************************************
    otp: ok: [otp]
    otp:
    otp: TASK [Update APT cache] ********************************************************
    otp: ok: [otp]
    otp:
    otp: TASK [azavea.pip : Install pip] ************************************************
    otp: ok: [otp]
    otp:
    otp: TASK [azavea.git : Install Git] ************************************************
    otp: ok: [otp]
    otp:
    otp: TASK [cac-tripplanner.transitfeed : Install pytz] ******************************
    otp: changed: [otp]
    otp:
    otp: TASK [cac-tripplanner.transitfeed : Install transitfeed] ***********************
    otp: changed: [otp]
    otp:
    otp: TASK [azavea.java : include] ***************************************************
    otp: skipping: [otp]
    otp:
    otp: TASK [azavea.java : include] ***************************************************
    otp: included: /tmp/packer-provisioner-ansible-local/roles/azavea.java/tasks/oracle.yml for otp
    otp:
    otp: TASK [azavea.java : Configure the WebUpd8 repository] **************************
    otp: changed: [otp]
    otp:
    otp: TASK [azavea.java : Accept Oracle license] *************************************
    otp: changed: [otp]
    otp:
    otp: TASK [azavea.java : Install Oracle Java] ***************************************
    otp: fatal: [otp]: FAILED! => {"cache_update_time": 0, "cache_updated": false, "changed": false, "failed": true, "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"     install 'oracle-java8-installer=8u111*'' failed: E: Version '8u111*' for 'oracle-java8-installer' was not found\n", "stderr": "E: Version '8u111*' for 'oracle-java8-installer' was not found\n", "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information..."]}
```

Instead of pinning Java versions (which requires a PR every time the PPA is updated), unpin the Java version and allow users to specify `java_version` and `java_major_version` in their own playbook variables.
